Repository 42-Gang/chat-server, pull requests merged in 2025-05, with the labels that each got.

#13 [FEATURE] dockerfile 추가
  .dockerignore
  Dockerfile
  package.json
  prisma/schema.prisma
  src/app.ts
  src/v1/index.ts
  src/v1/sockets/chat/chat.client.ts
  src/v1/sockets/chat/chat.manager.ts
  src/v1/sockets/chat/connection.handler.ts
  src/v1/sockets/chat/kafka/consumer.handler.ts
  src/v1/sockets/chat/kafka/consumer.ts
  src/v1/sockets/chat/kafka/messages.schema.ts
  src/v1/sockets/chat/kafka/producer.ts
  src/v1/sockets/utils/auth.ts
Labels: ✨ Feature, 🔨 Refactor

#15 [FEATURE] 로그아웃 이벤트 consume 핸들러 추가
  src/server-config.ts
  src/v1/sockets/chat/chat.schema.ts
  src/v1/sockets/chat/connection.handler.ts
  src/v1/sockets/chat/kafka/constants.ts
  src/v1/sockets/chat/kafka/consumer.handler.ts
  src/v1/sockets/chat/kafka/consumer.ts
  src/v1/sockets/chat/kafka/messages.schema.ts
  wiremock/mappings/get-user-nickname-1.json
  wiremock/mappings/token-verify.json
Labels: ✨ Feature

#22 Fix/20 채팅방 아이디 조회 api 수정
  src/v1/apis/chat.service.ts
  src/v1/apis/schemas/chat.schema.ts
Labels: 📬 API

#24 [FIX] message 페이로드 객체 그대로 받도록 수정
  src/v1/sockets/chat/connection.handler.ts
Labels: 🐞 BugFix
